package com.packt.sb5be.searchapp;

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Topic generated by hbm2java
 */
@Entity
@Table(name="topic"
    ,catalog="searchapp"
)
public class Topicc implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    private Long id;

    @Column(name="name", length=80)
    private String name;

    @Column(name="description", length=5000)
    private String description;

    @Column(name="text_field1", length=5000)
    private String textField1;

    @Column(name="text_field2", length=5000)
    private String textField2;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", length=26)
    private Date created;

    public Topicc() {
    }

    public Topicc(String name, String description, String textField1, String textField2, Date created) {
       this.name = name;
       this.description = description;
       this.textField1 = textField1;
       this.textField2 = textField2;
       this.created = created;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getTextField1() {
        return this.textField1;
    }

    public void setTextField1(String textField1) {
        this.textField1 = textField1;
    }

    public String getTextField2() {
        return this.textField2;
    }

    public void setTextField2(String textField2) {
        this.textField2 = textField2;
    }

    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }
}


